### ISSUE TITLE
[Curiosity] Asking is an upgrade is coming

### ISSUE THREAD

**Issue by Krands** [scith/tagspaces_ynh#5]
Hi,

I was thinking about replacing Turtl (which is nice but something is a bit off, I will wait and see) and Laverna (configuring multiple device sync is such a nightmare) and I got onto TagSpace. As I already have Yunohost, I am interested by TS now.

In your [README.md](https://github.com/scith/tagspaces_ynh/blob/master/README.md), you say:
> _The current version of the YNH TagSpaces app is v1.12.0. I will not update at the moment because the newer version has a different UI that conflicts with SSOwat (the file creation icone is placed under the YunoHost icon...)_

So I am just simply asking: is upgrading TagSpace to 2.xx part of your plans, or you will never do it ?

:beers:

**Comment by Krands** [comment]
**[Update] **
TagSpaces does not work on machines having less than 2Gb of RAM, believing the official docs.

**Comment by scith** [comment]
Hi, so what does not work exactly in a machine under 2b RAM? The app does not even launch?
As for the update, I could do the update and remove the SSOwat tile eventually. That is why in the manifest I left the option to install the latest version instead of the one I recommend.

**Comment by Krands** [comment]
Hi, no, it does not even launch. It's sort of stuck on the Tag logo, nothing else happens. Here's the **minimum** requirements. It's really a heavy software. Not even sure it would run on a Pine64.

>  **Linux**
    Intel® Pentium® 4 or AMD Athlon® processor
    Linux 32 or 64 bit
    2GB of RAM and 120MB of available hard-disk space
    1280x800 display resolution

[Source on TagSpaces' website](https://www.tagspaces.org/downloads/).
